// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'little-nimbus-app',
    appId: '1:343004667495:web:1168f3a85d2f04ab5cfec2',
    messagingSenderId: '343004667495',
    projectId: 'nimbus-6c5c4',
    authDomain: 'nimbus-6c5c4.firebaseapp.com',
    storageBucket: 'nimbus-6c5c4.firebasestorage.app',
    measurementId: 'G-NCQB7ENXNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'little-nimbus-app',
    appId: '1:343004667495:android:216082ce0fc72f355cfec2',
    messagingSenderId: '343004667495',
    projectId: 'nimbus-6c5c4',
    storageBucket: 'nimbus-6c5c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'little-nimbus-apps',
    appId: '1:343004667495:ios:41e8d1be798232725cfec2',
    messagingSenderId: '343004667495',
    projectId: 'nimbus-6c5c4',
    storageBucket: 'nimbus-6c5c4.firebasestorage.app',
    iosClientId: '343004667495-v08nlhb2fauvkovnrhb639i1fk0jq242.apps.googleusercontent.com',
    iosBundleId: 'com.example.clouds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPyc0vpclPrCKR7mmfgMdLyNsqejC4Bgs',
    appId: '1:343004667495:ios:41e8d1be798232725cfec2',
    messagingSenderId: '343004667495',
    projectId: 'nimbus-6c5c4',
    storageBucket: 'nimbus-6c5c4.firebasestorage.app',
    iosClientId: '343004667495-v08nlhb2fauvkovnrhb639i1fk0jq242.apps.googleusercontent.com',
    iosBundleId: 'com.example.clouds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'little-nimbus-app',
    appId: '1:343004667495:web:8bbb24584c990ec85cfec2',
    messagingSenderId: '343004667495',
    projectId: 'nimbus-6c5c4',
    authDomain: 'nimbus-6c5c4.firebaseapp.com',
    storageBucket: 'nimbus-6c5c4.firebasestorage.app',
    measurementId: 'G-VNG8PKCXLD',
  );
}
