name: clouds
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # แก้เป็นเวอร์ชัน SDK ที่รองรับ null safety

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^0.8.4+4
  image: ^3.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  google_fonts: ^6.1.0
  camera: ^0.10.6
  webview_flutter: ^4.0.7
  url_launcher: ^6.1.10
  google_maps_flutter: ^2.1.1
  carousel_slider: ^5.0.0
  path_provider: ^2.0.15  # รองรับ ffi ^1.x
  tflite_flutter: ^0.11.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.5.4
  share_plus: ^7.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo2.png
    - assets/c.webp
    - assets/stratus.jpg
    - assets/stratocumulus.jpg
    - assets/nimbostratus.jpg
    - assets/cumulus.jpg
    - assets/cumulonimbus.jpg
    - assets/cirrus.jpg
    - assets/cirrostratus.jpg
    - assets/cirrocumulus.jpg
    - assets/altostratus.jpg
    - assets/altocumulus.jpg
    - assets/cloud_model.tflite
    - assets/labels.txt
    - assets/google_icon.png
    - assets/bg.jpg
    - assets/bg1.jpg
    - assets/bg2.jpg

